#!/bin/bash

echo -e " MANAGE_CREDENTIALS \n -----------------------------------------------------"

read -p " INGRESA ARCHIVO DE CREDENCIALES: " PARAM_JSON_CREDENTIAL
PARAM_JSON_CREDENTIAL="${VARIABLE:-pulumi.json}"

export PARAM_JSON_CREDENTIAL=$PARAM_JSON_CREDENTIAL

export GOOGLE_CREDENTIALS=$(cat $PARAM_JSON_CREDENTIAL)

echo $GOOGLE_CREDENTIALS

echo -e " Credenciales exportadas correctamente\n"
